config/urls.py
"""project_management URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
# Django imports
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

import redmine_connector.views as rc_views
import earned_value_analysis.views as eva_views

urlpatterns = [
    # Examples:
    # url(r'^blog/', include('blog.urls', namespace='blog')),

    path('', rc_views.DashboardView.index, name="dashboard.index"),
    path('gantt/', rc_views.DashboardView.gantt_data, name="dashboard.gantt_data"),

    # provide the most basic login/logout functionality
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    # enable the admin interface
    url(r'^admin/', admin.site.urls, name="admin_view"),

    url(r'^connector/index', rc_views.index),
    url(r'^connector/all_projects', rc_views.get_all_redmine_projects),
    path('analysis/calculate', eva_views.calculate),
    path('analysis/calculate/all', eva_views.calculate_all),
    path('analysis/index/<slug:slug>', eva_views.index),
    path('meetings/', include('meeting_notes.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/meeting_notes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from simple_history.models import HistoricalRecords

from redmine_connector.models import RedmineProject
from earned_value_analysis.models import ProjectSection

# Create your models here.
class Meeting(models.Model):
    MEETING_STATUS = [
        ('NEW', 'NEW'),
        ('PLANNED', 'PLANNED'),
        ('IN PROGRESS', 'IN PROGRESS'),
        ('DONE', 'DONE')
    ]
    status = models.CharField(
        max_length=20,
        choices=MEETING_STATUS,
        default='NEW'
    )
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="meeting_creator")
    participants = models.ManyToManyField(User, related_name="meeting_participant")
    invite_automatically_by_mail = models.BooleanField(default=True)
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=5000, blank=True, null=True)
    start = models.DateTimeField()
    end = models.DateTimeField(default=None, null=True, blank=True)
    meeting_redmine_project = models.ForeignKey(RedmineProject, on_delete=models.CASCADE, default=None, blank=True, null=True)
    meeting_ticket_number = models.IntegerField(default=None, null=True, blank=True)
    auto_track_meeting_time = models.BooleanField(default=True)

    online_meeting_url = models.URLField(default=None, null=True, blank=True)
    offline_meeting_location = models.TextField(default=None, blank=True, null=True)

    is_closed = models.BooleanField(default=False)

    history = HistoricalRecords()

    def __str__(self):
        return self.title

class AgendaItem(models.Model):
    IMPORTANT_SCORE = [
        ('0', 'Not important'),
        ('1', 'Normal'),
        ('2', 'Important'),
        ('3', 'Very important')
    ]
    important_score = models.CharField(
        max_length=1,
        choices=IMPORTANT_SCORE,
        default='1'
    )
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = models.TextField(max_length=5000, default=None, null=True, blank=True)
    project_section = models.ForeignKey(ProjectSection, on_delete=models.CASCADE, blank=True, null=True, default=None)

    is_done = models.BooleanField(default=False)
    done_timestamp = models.DateTimeField(blank=True, null=True, default=None)

    history = HistoricalRecords()

    def __str__(self):
        return str(self.id) + " | " + self.title

class Note(models.Model):
    TYPE_CHOICES = [
        ('NOTE', 'NOTE'),
        ('DECISION', 'DECISION'),
        ('OPTIONS', 'OPTIONS'),
        ('INFORMATION', 'INFORMATION'),
        ('PROGRESS', 'PROGRESS INFORMATION'),
        ('TBD', 'TO BE DECIDED')
    ]
    note_type = models.CharField(
        max_length=20,
        choices=TYPE_CHOICES,
        default='NOTE',
    )
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    agenda_item = models.ForeignKey(AgendaItem, on_delete=models.CASCADE, blank=True, null=True, default=None)
    project_section = models.ForeignKey(ProjectSection, on_delete=models.CASCADE, blank=True, null=True, default=None)
    text = models.TextField(max_length=5000)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="note_creator")
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name="note_assignee", blank=True, null=True, default=None)
    connect_to_ticket = models.IntegerField(blank=True, null=True, default=None)
    is_private_note = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now=True)

    due_date = models.DateField(null=True, blank=True, default=None)

    is_done = models.BooleanField(default=False)
    done_timestamp = models.DateTimeField(blank=True, null=True, default=None)

    history = HistoricalRecords()

    is_dependent_on = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, default=None)

    def __str__(self):
        return self.creator.username + " / " + str(self.note_type) + " " + self.text[:10] + " (" + str(self.pk) + ")"


class Comment(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    text = models.TextField(max_length=5000)
    timestamp = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)


class TodoistConnector(models.Model):
    connected_user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    api_token = models.CharField(max_length=255)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.connected_user.first_name + " " + self.connected_user.last_name


class TimeEstimate(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time_estimate = models.FloatField()
    time_estimate_in_slots = models.IntegerField(default=None, null=True, blank=True)


class SprintUserSettings(models.Model):
    connected_user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    sprint_length_in_days = models.IntegerField()
    blocked_time_in_hours = models.IntegerField(null=True, blank=True, default=None) # meant for weekends at 7 day sprints
    work_time_mondays = models.IntegerField(default=8)
    work_time_tuesdays = models.IntegerField(default=8)
    work_time_wednesdays = models.IntegerField(default=8)
    work_time_thursdays = models.IntegerField(default=8)
    work_time_fridays = models.IntegerField(default=8)
    work_time_saturdays = models.IntegerField(default=0)
    work_time_sundays = models.IntegerField(default=0)

    def __str__(self):
        return self.connected_user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        SprintUserSettings.objects.create(
            connected_user=instance,
            sprint_length_in_days=7
        )

    
class Sprint(models.Model):
    connected_user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    sprint_id = models.CharField(max_length=100)
    tasks = models.CharField(max_length=5000, default=None, blank=True, null=True)

    def __str__(self):
        return self.connected_user.username + "_" + str(self.sprint_id)

templates/partials/agenda_item.html
<h4 class="ui dividing header">
  <span style="font-size: 15px;">
    {% if agenda_item.important_score == '0' %}
      <i class="exclamation circle icon blue"></i>
    {% elif agenda_item.important_score == '1' %}
      <i class="exclamation circle icon green"></i>
    {% elif agenda_item.important_score == '2' %}
      <i class="exclamation circle icon yellow"></i>
    {% elif agenda_item.important_score == '3' %}
      <i class="exclamation circle icon red"></i>
    {% endif %}
  </span>
  {{ agenda_item.title }}
</h4>
<div class="item">
  <div class="ui comments">
    <div class="comment">
      <div class="content">
        {% if agenda_item.is_done %}
          <div class="metadata">
            <i class="check icon green"></i><span>{{ agenda_item.done_timestamp|date:"d.m.Y H:i:s" }}</span>
            <br />
          </div>
        {% endif %}
        <div class="text">
          {{ agenda_item.text }}
        </div>
        <div class="actions">
          <a class="reply" onclick="editItem('{{ agenda_item.id }}')">Edit</a>
          <a class="reply" onclick="deleteItem('{{ agenda_item.id }}')">Delete</a>
          {% if not agenda_item.is_done %}
            <a class="save">Alert</a>
            <a class="hide" onclick="markDone('{{ agenda_item.id }}')">Mark as done</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

templates/partials/default_form.html
{% load widget_tweaks %}
<form method="post" class="ui form" {% if form_action %}action="{{ form_action }}"{% endif %}>
  {% csrf_token %}

  {% for hidden in form.hidden_fields %}
    {{ hidden }}
  {% endfor %}

  {% for field in form.visible_fields %}
    <div class="field">
      {% for error in field.errors %}
        <div class="ui pointing below red basic label">
          {{ error }}
        </div>
      {% endfor %}
      {% if 'checkbox' in field.field.widget.input_type %}
        <div class="ui checkbox">
          {{ field }}
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        </div>
      {% else %}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
      {% endif %}
    </div>
  {% endfor %}

  <div class="ui one bottom attached buttons">
    <button type="submit" class="ui button primary">Save</button>
  </div>
</form>

templates/partials/footer.html
<div class="ui inverted vertical footer segment">
  <div class="ui center aligned container">
    <div class="ui stackable inverted divided grid">
      <div class="three wide column">
        <h4 class="ui inverted header">Group 1</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Link One</a>
          <a href="#" class="item">Link Two</a>
          <a href="#" class="item">Link Three</a>
          <a href="#" class="item">Link Four</a>
        </div>
      </div>
      <div class="three wide column">
        <h4 class="ui inverted header">Group 2</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Link One</a>
          <a href="#" class="item">Link Two</a>
          <a href="#" class="item">Link Three</a>
          <a href="#" class="item">Link Four</a>
        </div>
      </div>
      <div class="three wide column">
        <h4 class="ui inverted header">Group 3</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Link One</a>
          <a href="#" class="item">Link Two</a>
          <a href="#" class="item">Link Three</a>
          <a href="#" class="item">Link Four</a>
        </div>
      </div>
      <div class="seven wide column">
        <h4 class="ui inverted header">Footer Header</h4>
        <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
      </div>
    </div>
    <div class="ui inverted section divider"></div>
    <img src="assets/images/logo.png" class="ui centered mini image">
    <div class="ui horizontal inverted small divided link list">
      <a class="item" href="#">Site Map</a>
      <a class="item" href="#">Contact Us</a>
      <a class="item" href="#">Terms and Conditions</a>
      <a class="item" href="#">Privacy Policy</a>
    </div>
  </div>
</div>

templates/partials/header.html
<div class="ui fixed inverted menu">
  <div class="ui container">
    <a href="#" class="header item">
      <img class="logo" src="https://www.decolore.net/wp-content/uploads/2018/09/50-incredible-3d-logo-design-examples-for-inspiration-cover.png">
      &nbsp;&nbsp;&nbsp;{% block title %}Documentor{% endblock %}
    </a>
    {% if user.is_authenticated %}
      <a href="/" class="item">Home</a>
      <div class="ui simple dropdown item">
        Meetings <div class="ui label teal">23</div> <i class="dropdown icon"></i>
        <div class="menu">
          <a class="item" href="{% url 'meetings.index' %}">Overview</a>
          <a class="item" href="{% url 'notes.own' %}">Own Notes</a>
        </div>
      </div>
      <div class="right menu">
        <div class="ui simple dropdown item">
          User <i class="dropdown icon"></i>
          <div class="menu">
            <a class="item" href="{% url 'meetings.index' %}">Profile</a>
            {% if user.is_superuser %}
              <a href="/admin" class="item">Admin</a>
            {% endif %}
          </div>
        </div>
        <a class="ui item" href="{% url 'logout' %}">
          Logout
        </a>
      </div>
    {% else %}
      <div class="right menu">
        <a class="ui item" href="{% url '/admin/login' %}">
          Login
        </a>
      </div>
    {% endif %}
  </div>
</div>

templates/partials/note.html
{% for agenda_item, note_qs in notes.items %}
<h4 class="ui dividing header">
  <span style="font-size: 15px;">
    {% if agenda_item.important_score == '0' %}
      <i class="exclamation circle icon blue"></i>
    {% elif agenda_item.important_score == '1' %}
      <i class="exclamation circle icon green"></i>
    {% elif agenda_item.important_score == '2' %}
      <i class="exclamation circle icon yellow"></i>
    {% elif agenda_item.important_score == '3' %}
      <i class="exclamation circle icon red"></i>
    {% endif %}
  </span>
  {{ agenda_item.title }}
</h4>
  {% if note_qs|length > 0 %}
    {% for note in note_qs %}
    <div class="ui comments" style="margin-left: 10px;">
      <div class="comment">
        <div class="content">
          <a class="author">{{ note.creator }}</a>
          <div class="metadata">
            {% if note.assigned_to %}
              <div class="date">Assigned: @{{ note.assigned_to }}</div>
            {% endif %}
            {% if note.connect_to_ticket %}
              <div class="rating">
                <a href=""><i class="ticket icon"></i>
                {{ note.connect_to_ticket }}
              </div></a>
            {% endif %}
            {% if note.is_done %}
              <i class="check icon green"></i><span>{{ note.timestamp|date:"d.m.Y H:i:s" }}</span>
            {% endif %}
          </div>
          <div class="text">
            {{ note.text }}
          </div>
          <div class="actions">
            <a class="reply" onclick="editItem('{{ note.id }}')">Edit</a>
            <a class="reply" onclick="deleteItem('{{ note.id }}')">Delete</a>
            <a class="reply" onclick="newComment('{{ note.id }}')">Comment</a>
            {% if not note.is_done %}
              <a class="save">Alert</a>
              <a class="hide" onclick="markDone('{{ note.id }}')">Mark as done</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% for comment in note.comment_set.all %}
      <div class="ui comments" style="margin-left: 50px;">
        <div class="comment">
          <div class="content">
            <a class="author">{{ comment.creator }}</a>
            <div class="text">
              {{ comment.text }}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    {% endfor %}
  {% else %}
  <div class="ui comments" style="margin-left: 10px;">
    <div class="comment">
      <div class="content">
        No notes for this point
      </div>
    </div>
  </div>
  {% endif %}
  <button class="ui basic button" onclick="showNewNoteModal('{{ agenda_item.pk }}');" style="width: 100%">
    <i class="icon add"></i>
    Add New
  </button>
{% endfor %}

templates/partials/tabs.html
<div class="ui steps" style="width: 100%;">
  <div 
    class="step {% if 'meeting' in section %}active{% else %}completed{% endif %}" 
    {% if meeting_id %}
      onclick="window.location.href = '{% url 'meetings.edit' meeting_id %}'"
    {% endif %}>
    <i class="users icon"></i>
    <div class="content">
      <div class="title">Meeting</div>
      <div class="description">Basic information about the meeting</div>
    </div>
  </div>
  <div 
    class="step {% if 'agenda_item' in section %}active{% elif 'meeting' in section %}disabled{% else %}completed{% endif %}"
    {% if meeting_id %}
      onclick="window.location.href = '{% url 'agenda_item.create' meeting_id %}'"
    {% endif %}>
    <i class="clipboard list icon"></i>
    <div class="content">
      <div class="title">Agenda Item</div>
      <div class="description">Planned points to cover in meeting</div>
    </div>
  </div>
  <div 
    class="step {% if 'note' in section %}active{% elif 'agenda_item' in section or 'meeting' in section %}disabled{% endif %}"
    {% if meeting_id %}
      onclick="window.location.href = '{% url 'notes.create' meeting_id %}'"
    {% endif %}>
    <i class="sticky note outline icon"></i>
    <div class="content">
      <div class="title">Notes</div>
      <div class="description">Notes for the meeting</div>
    </div>
  </div>
</div>